[package]
name = "fred_mortgage_data"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
fred-rs = "0.1.1"
prettytable-rs = "0.10.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
